#ifndef COCAPTURE_CAMERA_H
#define COCAPTURE_CAMERA_H

namespace Cocapture {

    // Camera types
    enum {
        CAM_TYPE_NONE,
        CAM_TYPE_BASLER,
        CAM_TYPE_PROPHESEE,
    };

    // Prophesee cameras
    enum {
        PROPHESEE_INFO_SERIAL,
        PROPHESEE_INFO_INTEGRATOR,
        PROPHESEE_INFO_PLUGIN,
        PROPHESEE_INFO_GENERATION,
        PROPHESEE_INFO_RAW_FORMATS,

        PROPHESEE_SYNC_MODE,
        PROPHESEE_MODE_STANDALONE,
        PROPHESEE_MODE_MASTER,
        PROPHESEE_MODE_SLAVE,

        PROPHESEE_GEOMETRY_WIDTH,
        PROPHESEE_GEOMETRY_HEIGHT,

        PROPHESEE_BIAS_DIFF_ON,
        PROPHESEE_BIAS_DIFF_ON_MIN,
        PROPHESEE_BIAS_DIFF_ON_MAX,

        PROPHESEE_BIAS_DIFF_OFF,
        PROPHESEE_BIAS_DIFF_OFF_MIN,
        PROPHESEE_BIAS_DIFF_OFF_MAX,

        PROPHESEE_BIAS_FO,
        PROPHESEE_BIAS_FO_MIN,
        PROPHESEE_BIAS_FO_MAX,

        PROPHESEE_BIAS_HPF,
        PROPHESEE_BIAS_HPF_MIN,
        PROPHESEE_BIAS_HPF_MAX,

        PROPHESEE_BIAS_REFR,
        PROPHESEE_BIAS_REFR_MIN,
        PROPHESEE_BIAS_REFR_MAX,

        // For internal use only
        PROPHESEE_GUI_TITLE,
        PROPHESEE_GUI_TEXTURE,
        PROPHESEE_GUI_PATH,
        PROPHESEE_GUI_TRIGGERS
    };

    // Basler cameras
    enum {
        BASLER_INFO_SERIAL,
        BASLER_INFO_MODEL,
        BASLER_INFO_VENDOR,

        BASLER_TRIGGER_SELECTOR,
        BASLER_TRIGGER_SOURCE,
        BASLER_TRIGGER_ACTIVATION,

        BASLER_DIM_WIDTH,
        BASLER_DIM_HEIGHT,

        BASLER_EXPOSURE_TIME,

        BASLER_TRIGGER_MODE,

        // For internal use only
        BASLER_GUI_TITLE,
        BASLER_GUI_TEXTURE,
        BASLER_GUI_PATH,
        BASLER_GUI_FRAMES
    };

    enum {
        BASLER_TRIGGER_SELECTOR_FRAME_START,
        BASLER_TRIGGER_SELECTOR_FRAME_END,
        BASLER_TRIGGER_SELECTOR_FRAME_ACTIVE,

        BASLER_TRIGGER_SELECTOR_FRAME_BURST_START,
        BASLER_TRIGGER_SELECTOR_FRAME_BURST_END,
        BASLER_TRIGGER_SELECTOR_FRAME_BURST_ACTIVE,

        BASLER_TRIGGER_SELECTOR_EXPOSURE_START,
        BASLER_TRIGGER_SELECTOR_EXPOSURE_END,
        BASLER_TRIGGER_SELECTOR_EXPOSURE_ACTIVE,

        BASLER_TRIGGER_SOURCE_LINE1,
        BASLER_TRIGGER_SOURCE_LINE2,
        BASLER_TRIGGER_SOURCE_LINE3,
        BASLER_TRIGGER_SOURCE_LINE4,
        BASLER_TRIGGER_SOURCE_LINE5,
        BASLER_TRIGGER_SOURCE_LINE6,

        BASLER_TRIGGER_ACTIVATION_RISING_EDGE,
        BASLER_TRIGGER_ACTIVATION_FALLING_EDGE,
        BASLER_TRIGGER_ACTIVATION_ANY_EDGE,

        BASLER_TRIGGER_ACTIVATION_LEVEL_HIGH,
        BASLER_TRIGGER_ACTIVATION_LEVEL_LOW,

        BASLER_EXPOSURE_TIME_MIN,
        BASLER_EXPOSURE_TIME_MAX,

        BASLER_TRIGGER_MODE_ON,
        BASLER_TRIGGER_MODE_OFF,
    };

} // Cocapture

#endif //COCAPTURE_CAMERA_H